spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

Comment:
   avatar: /images/avatar.png
   
Message:
    avatar: /images/avatar.png

User:
  avatar: /images/avatar.png
  introduction: "孩子害羞，还没添加简介"